theme: jekyll-theme-slate
baseurl: '/MDunmeris/' # the subpath of your site, e.g. /blog
url: 'https://mmillar-bolis.github.io' # the base hostname & protocol for your site, e.g. http://example.com
title: '[MD]unmeris'
description: 'A GitHub Markdown Repository for Morrowind Related Documents'
show_downloads: false
